logstash:
  extends:
    file: common.yml
    service: logstash
  links:
  - elastic

mongodb:
  extends:
    file: common.yml
    service: mongodb

redis:
  extends:
    file: common.yml
    service: redis

kibana:
  extends:
    file: common.yml
    service: kibana
  links:
  - elastic

elastic:
  extends:
    file: common.yml
    service: elastic

postfix:
  extends:
    file: common.yml
    service: postfix

backend:
  extends:
    file: common.yml
    service: backend
  links:
   - mongodb
   - redis
   - elastic
   - logstash
   - postfix
  environment:
   - SUPERDESK_RELOAD=True
   - SUPERDESK_URL=http://localhost:5000/api
   - SUPERDESK_CLIENT_URL=http://localhost:9000
  volumes:
   - ../server:/opt/superdesk/
  ports:
   - "5000:5000"
   - "5100:5100"

frontend:
  extends:
    file: common.yml
    service: frontend
  links:
   - backend
  command: sh -c "grunt --force server --server='http://localhost:5000/api' --ws='ws://localhost:5100'"
  volumes:
   - ../client:/opt/superdesk-client/
  ports:
   - "9000:9000"
   - "35729:35729"
